# Self created Image of National Flag

In [1]:
import cv2
import numpy as np

In [2]:
#Set Dimensions
Flag = np.zeros((600, 1000, 3), dtype="uint8")

In [3]:
#Set National Flag Colors
orange = (0, 165, 255)
white = (255,255,255)
green = (0,128,0)
blue = (255,0,0)
gray = (192,192,192)

In [4]:
#Create rectangles and fill with tri-colors
cv2.rectangle(Flag, (400, 100), (600, 120), orange, 20)
cv2.rectangle(Flag, (400, 140), (600, 160), white, 20)
cv2.rectangle(Flag, (400, 180), (600, 200), green, 20)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [5]:
#Create Vertical pole 
cv2.rectangle(Flag, (380, 80), (385, 500), gray, 5)
cv2.circle(Flag, (380,80) , 5, gray, 3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [6]:
#Draw Ashoka Chakra with circle
cv2.circle(Flag, (500,150) , 15, blue, 2)
cv2.circle(Flag, (500,150) , 1, blue, 2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
#Draw 24 spokes of Ashok Chakra

cv2.line(Flag, (485,150), (515,150), blue, 1) 
cv2.line(Flag, (500,135), (500,165), blue, 1) 
cv2.line(Flag, (491,141), (510,163), blue, 1) 
cv2.line(Flag, (494,139), (505,163), blue, 1) 
cv2.line(Flag, (496,138), (502,162), blue, 1) 
cv2.line(Flag, (503,133), (499,161), blue, 1) 
cv2.line(Flag, (507,135), (495,161), blue, 1) 
cv2.line(Flag, (510,138), (493,159), blue, 1) 
cv2.line(Flag, (515,140), (489,157), blue, 1) 
cv2.line(Flag, (515,142), (486,155), blue, 1) 
cv2.line(Flag, (488,147), (500,150), blue, 1) 
cv2.line(Flag, (500,150), (515,155), blue, 1) 
cv2.line(Flag, (500,150), (512,148), blue, 1) 
cv2.line(Flag, (500,150), (512,157), blue, 1) 
cv2.line(Flag, (487,161), (512,138), blue, 1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [ ]:
#Final Image
cv2.imshow("Flag", Flag)
cv2.waitKey(0)
cv2.destroyAllWindows()